language: python
python:
    - "3.5"

dist: bionic
sudo: required

addons:
  apt:
    packages:
      - git
install:
  - pip install -r requirements.txt
  - pip install pylava
  - pip install python-coveralls

before_script:
  - pylava

script:
  - coverage run --source=atomicgraphs/ -a tests/compareParseData.py
  - coverage run --source=atomicgraphs/ -a tests/test_simpleisomorphism.py
  - coverage run --source=atomicgraphs/ -a tests/test_utils.py
  - coverage run --source=atomicgraphs/ -a tests/test_diff.py

after_success:
  - coverage report -m
  - coveralls
