language: python
python:
    - "3.5"

dist: bionic
sudo: required

addons:
  apt:
    packages:
      - git
install:
  - pip install -r requirements.txt
  - pip install pylava
  - pip install python-coveralls

before_script:
  - pylava

script:
  - coverage run --source=atomicgraphs/ -a tests/compareParseData.py
  - coverage run --source=atomicgraphs/ -a tests/test_simpleisomorphism.py
  - coverage run --source=atomicgraphs/ -a tests/test_utils.py
  - coverage run --source=atomicgraphs/ -a tests/test_diff.py
  - coverage run --source=atomicgraphs/ -a tests/test_conjunctive_graph.py
  - coverage run --source=atomicgraphs/ -a tests/test_selective_comparable_graph.py

after_success:
  - coverage report -m
  - coveralls

deploy:
  provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  on:
    tags: true
